import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from './banner/banner'
import NextTrain from './NextRail/nextTrain'

export default function Home() {
  Head('Dhaka Metro')
  return (
    <div className={styles.container}>
      <Head>
        <title>Dhaka Metro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner></Banner>
      <NextTrain></NextTrain>
    </div>
  )
}
